import { PlaceHolderImages } from '@/lib/placeholder-images';

export const facilitiesData = [
  {
    name: "District Hospital, Paderu",
    type: "Government (District Hospital/CHC)",
    location: "Paderu (district headquarters)",
    bedAvailability: "Beds Available",
    specialists: ["In-patient Care", "Deliveries", "Basic Specialties", "Referral Point"],
    contact: "08935-250123",
    image: PlaceHolderImages.find(img => img.id === 'hospital-facility'),
    details: "Main government referral hospital for the district; handles in-patient care, deliveries and basic specialties; used as coordination point for district health services.",
  },
  {
    name: "Community Health Centre / CHC, Paderu",
    type: "Government (CHC)",
    location: "Paderu, Alluri Sitarama Raju district",
    bedAvailability: "N/A",
    specialists: ["Outpatient", "Immunization", "Basic Emergency"],
    contact: "9876543211",
    image: null,
    details: "Primary community health centre offering outpatient, immunization and basic emergency services.",
  },
  {
    name: "Area Hospital — Araku / Araku Valley",
    type: "Area Hospital / CHC",
    location: "Araku Valley (Dumbriguda / Pachipenta area)",
    bedAvailability: "24x7 Available",
    specialists: ["Emergency", "Referral Point"],
    contact: "9876543212",
    image: PlaceHolderImages.find(img => img.id === 'hospital-facility'),
    details: "24×7 area hospital serving Araku Valley — important referral point for tribal pockets and tourist route.",
  },
  {
    name: "Area Hospital — Rampachodavaram",
    type: "Area Hospital",
    location: "Rampachodavaram",
    bedAvailability: "Beds Available",
    specialists: ["Emergency", "Inpatient Care"],
    contact: "9876543213",
    image: null,
    details: "Area hospital handling emergencies and inpatient care for surrounding mandals.",
  },
  {
    name: "CHC — Munchingi Puttu",
    type: "CHC",
    location: "Munchingi Puttu / Munchingput mandal",
    bedAvailability: "N/A",
    specialists: ["Rural Health", "Local Referrals"],
    contact: "9876543214",
    image: null,
    details: "Rural CHC serving nearby tribal habitations; useful for local referrals.",
  },
   {
      name: "CHC — G. Madugula",
      type: "CHC",
      location: "G. Madugula / Gemmili",
      bedAvailability: "N/A",
      specialists: ["Rural Health", "PHC Services"],
      contact: "9876543215",
      image: null,
      details: "Rural CHC listed in state PHC/CHC maps (serves eastern mandals).",
  },
  {
    name: "Araku Railway Hospital",
    type: "Railway hospital / public facility",
    location: "Araku (near railway/station area)",
    bedAvailability: "Limited",
    specialists: ["Basic Care", "Public Access"],
    contact: "9876543216",
    image: null,
    details: "Small facility supporting rail employees and sometimes local patients; useful in Araku township.",
  },
  {
    name: "Alluri Sitarama Raju Academy of Medical Sciences (ASRAM)",
    type: "Medical college & teaching hospital",
    location: "Eluru (Verify location)",
    bedAvailability: "Varies",
    specialists: ["Specialist Referrals", "Teaching Hospital"],
    contact: "9876543217",
    image: null,
    details: "Medical college & attached teaching hospital. Note: ASRAM in multiple listings appears associated with Eluru region — verify physical location relative to ASR district before routing emergency referrals.",
  },
  {
    name: "Sai Sri Clinic & Diagnostics",
    type: "Private Clinic",
    location: "Rajavommangi",
    bedAvailability: "N/A",
    specialists: ["Diagnostics", "General Clinic"],
    contact: "9876543218",
    image: null,
    details: "Registered private healthcare establishment in OCMMMS registry.",
  },
   {
    name: "Devi Clinic (Paderu area)",
    type: "Private Clinic",
    location: "Paderu",
    bedAvailability: "N/A",
    specialists: ["General Clinic"],
    contact: "9876543219",
    image: null,
    details: "Local clinic with phone and street address listed in local directories.",
  },
  {
    name: "Tejasri Clinic",
    type: "Private Clinic",
    location: "Araku",
    bedAvailability: "N/A",
    specialists: ["General Clinic"],
    contact: "9876543220",
    image: null,
    details: "Local listing shows clinic and phone.",
  },
  {
    name: "AREA HOSPITAL - ARAKU",
    type: "Area Hospital",
    location: "Araku Valley - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["CRITICAL CARE", "ENT SURGERY", "GENERAL MEDICINE", "GENERAL SURGERY", "GYNAECOLOGY AND OBSTETRICS SURGERY", "OPHTHALMOLOGY SURGERY", "ORTHOPEDIC SURGERY AND PROCEDURES", "PEDIATRICS", "POLY TRAUMA"],
    contact: "9281069587",
    image: null,
    details: "Address: Kantabamsuguda Araku Valley, PIN-532149",
  },
  {
    name: "AREA HOSPITAL - CHINTAPALLI",
    type: "Area Hospital",
    location: "CHINTAPALLI - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["ENT SURGERY", "GENERAL SURGERY", "GYNAECOLOGY AND OBSTETRICS SURGERY", "ORTHOPEDIC SURGERY AND PROCEDURES", "PEDIATRICS"],
    contact: "9281069634",
    image: null,
    details: "Address: Chintapalli, PIN-531111",
  },
  {
    name: "AREA HOSPITAL - RAMPACHODAVARAM",
    type: "Area Hospital",
    location: "Rampachodavaram - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["ENT SURGERY", "GENERAL MEDICINE", "GENERAL SURGERY", "GYNAECOLOGY AND OBSTETRICS SURGERY", "OPHTHALMOLOGY SURGERY", "ORTHOPEDIC SURGERY AND PROCEDURES", "PEDIATRICS", "POLY TRAUMA"],
    contact: "9281068470",
    image: null,
    details: "Address: devipatnam road, HIGH SCHOOL, PIN-533288",
  },
  {
    name: "CHC -ADDATEEGALA",
    type: "CHC",
    location: "Addateegala - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["GENERAL MEDICINE", "GYNAECOLOGY AND OBSTETRICS SURGERY", "INFECTIOUS DISEASES", "PEDIATRICS"],
    contact: "9281068449",
    image: null,
    details: "Address: postoffice road, POST OFFICE, PIN-533428",
  },
  {
    name: "CHC -CHINTOOR",
    type: "CHC",
    location: "CHINTOOR - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["ENT SURGERY", "GENERAL MEDICINE", "GYNAECOLOGY AND OBSTETRICS SURGERY", "ORTHOPEDIC SURGERY AND PROCEDURES", "PEDIATRICS"],
    contact: "9281068541",
    image: null,
    details: "Address: Sub station opp, Ratnapuram, Near ITDA Road, PIN-507713",
  },
  {
    name: "CHC -KUNAVARAM",
    type: "CHC",
    location: "Kunavaram - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["GENERAL SURGERY", "GYNAECOLOGY AND OBSTETRICS SURGERY"],
    contact: "9281068479",
    image: null,
    details: "Address: Kothulagutta, MAIN ROAD, PIN-533350",
  },
  {
    name: "CHC -MUNCHINGIPUTTU",
    type: "CHC",
    location: "MUNCHINGAPUTTU - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"],
    contact: "9281069654",
    image: null,
    details: "Address: Munchingiputtu, PIN-531040",
  },
  {
    name: "CHC -Y RAMAVARAM",
    type: "CHC",
    location: "Y.Ramavaram - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["GENERAL MEDICINE", "GENERAL SURGERY", "GYNAECOLOGY AND OBSTETRICS SURGERY", "ORTHOPEDIC SURGERY AND PROCEDURES", "PEDIATRICS"],
    contact: "9281068519",
    image: null,
    details: "Address: Y RAMAVARAM, Police station road, PIN-533483",
  },
  {
    name: "GOVERNMENT GENERAL HOSPITAL - PADERU",
    type: "Government General Hospital",
    location: "Paderu - R, ALLURI SITHARAMA RAJU",
    bedAvailability: "Unknown",
    specialists: ["CRITICAL CARE", "DERMATOLOGY", "ENT SURGERY", "GENERAL MEDICINE", "GENERAL SURGERY", "GYNAECOLOGY AND OBSTETRICS SURGERY", "OPHTHALMOLOGY SURGERY", "ORTHOPEDIC SURGERY AND PROCEDURES", "PEDIATRICS", "PSYCHIATRY"],
    contact: "9281069705",
    image: null,
    details: "Address: 15001, Sundruputtu Paderu, PIN-521024",
  },
  { name: "PHC -ANANTHAGIRI", type: "PHC", location: "Ananthagiri - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: PHC Ananthagiri" },
  { name: "PHC -BHEEMAVARAM", type: "PHC", location: "Ananthagiri - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: BHEEMAVARAM GUMMAKOTA SACHIVA" },
  { name: "PHC -BODULURU", type: "PHC", location: "Maredumilli - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Chatlawada Road, PIN-533295" },
  { name: "PHC -CHAVITIDIBBALU", type: "PHC", location: "Y.Ramavaram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: main road, YRamavaram, PIN-533483" },
  { name: "PHC -DARAKONDA", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: DARAKONDA MAINROAD DARAKONAD" },
  { name: "PHC -DEVIPATNAM", type: "PHC", location: "Devipatnam - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: DEVIPATNAM Main road, PIN-533286" },
  { name: "PHC -DOWNURU", type: "PHC", location: "Koyyuru - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: 1-1" },
  { name: "PHC -DUMBRIGUDA", type: "PHC", location: "Dumbriguda - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: PHC DUMBRIGUDA" },
  { name: "PHC -DUPPULAPALEM", type: "PHC", location: "Addateegala - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: main road, YRamavaram, PIN-533428" },
  { name: "PHC -EDUGURALLAPALLI", type: "PHC", location: "CHINTOOR - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: EDUGURALLAPALLY VILLAGE CHINTOOR MANDAL 533347" },
  { name: "PHC -EEDULAPALEM", type: "PHC", location: "Paderu - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: EEDHULAPALEM VILLAGEPADERU M" },
  { name: "PHC -G MADUGULA", type: "PHC", location: "G.Madugula - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: G MADUGULA" },
  { name: "PHC -G.K.VEEDHI", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: GKVEEDHI" },
  { name: "PHC -GANGAVARAM", type: "PHC", location: "GANGAVARAM AGENCY - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: 1" },
  { name: "PHC -GANNELA", type: "PHC", location: "Araku Valley - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: GANNELA VILLAGE ARAKUVALLEY" },
  { name: "PHC -GEMMELI", type: "PHC", location: "G.Madugula - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: GEMMELI G MADUGULA MANDAL VI" },
  { name: "PHC -GOMANGI", type: "PHC", location: "Pedabayalu - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: GOMANGI" },
  { name: "PHC -GOWRIDEVIPETA", type: "PHC", location: "Nellipaka - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: GOWRIDEVIPETA VILLAGE YETAPAKA MANDAL 533352" },
  { name: "PHC -GURTHEDU", type: "PHC", location: "Y.Ramavaram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Near Ashram School, Gurthedu, PIN-533483" },
  { name: "PHC -HUKUMPETA", type: "PHC", location: "Hukumpeta - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: HUKUMPETA MANDALAM VISAKHAPA" },
  { name: "PHC -INDUKURUPETA", type: "PHC", location: "Devipatnam - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: PHC INDUKURUPETA 533286" },
  { name: "PHC -JEEDI GUPPA", type: "PHC", location: "Vararamachandrapuram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Jeediguppavr puram, EGAP" },
  { name: "PHC -JERRILA", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: JERRILA VILLAGE GKVEEDHI MA" },
  { name: "PHC -KANTARAM", type: "PHC", location: "Koyyuru - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: KANTARAM VILLAGE KOYYURU MD" },
  { name: "PHC -KILAGADA", type: "PHC", location: "MUNCHINGAPUTTU - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: KILAGADA VILLAGE MUCHINGIPUT" },
  { name: "PHC -KILLOGUDA", type: "PHC", location: "Dumbriguda - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Killoguda Village Sagara Post" },
  { name: "PHC -KONDAMODALU", type: "PHC", location: "Devipatnam - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Near Godavari Kondamodalu Pin-533286" },
  { name: "PHC -KORUKONDA", type: "PHC", location: "CHINTAPALLI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Korukonda Chinthapalli M V" },
  { name: "PHC -KUTURU", type: "PHC", location: "Kunavaram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: KUTURU VILLAGE KUNAVARAM MANDAL 533289" },
  { name: "PHC -LABBURU", type: "PHC", location: "MUNCHINGAPUTTU - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: LABBURU VILLAGE MUCHINGIPUTT" },
  { name: "PHC -LAGARAI", type: "PHC", location: "Rajavommangi - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: OPPOSITE DURGA TEMPLE, LAGARAI, PIN CODE-533436" },
  { name: "PHC -LAMBASING", type: "PHC", location: "CHINTAPALLI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: LAMBASINGI VILAGE CHINTHAPALL" },
  { name: "PHC -LAXMIPURAM", type: "PHC", location: "Devipatnam - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: LAXMIPURAM VILLAGE YETAPAKA MANDAL 533352" },
  { name: "PHC -LOTHUGEDDA", type: "PHC", location: "CHINTAPALLI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: LOTHUGEDDA" },
  { name: "PHC -LUNGAPARTHI", type: "PHC", location: "Ananthagiri - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: LUNGAPARTHI VILLAGE" },
  { name: "PHC -MADAGADA", type: "PHC", location: "Araku Valley - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: MADAGADA VILLAGE" },
  { name: "PHC -MAREDUMILLI", type: "PHC", location: "Maredumilli - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Near Andhra Bank Maredumilli PIN-533295" },
  { name: "PHC -MINUMULURU", type: "PHC", location: "Paderu - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: MINUMULURU VILLAGE PADERU MA" },
  { name: "PHC -NARASAPURAM", type: "PHC", location: "Rampachodavaram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: PHC NARASAPURAM, MAIN ROAD, RAMPACHODAVRAM, 533288" },
  { name: "PHC -P.GEDDADA", type: "PHC", location: "Rampachodavaram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: PHC Pedageddada" },
  { name: "PHC -PEDABAYALU", type: "PHC", location: "Pedabayalu - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: pedabayalu phc" },
  { name: "PHC -PEDAVALASA", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Pedavalasa Village GK Veedh" },
  { name: "PHC -PIDATHAMAMIDI", type: "PHC", location: "GANGAVARAM AGENCY - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Near MPP school pidathamamidi 533285" },
  { name: "PHC -PINAKOTA", type: "PHC", location: "Ananthagiri - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: PHC Pinakota, Main Road, PINCODE-531030" },
  { name: "PHC -R V NAGAR", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: R V NAGAR VILLAGE AND POST" },
  { name: "PHC -RAJAVOMMANGI", type: "PHC", location: "Rajavommangi - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "9281068589", image: null, details: "Address: Pin code 518422" },
  { name: "PHC -RAJENDRAPALEM", type: "PHC", location: "Koyyuru - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: RAJENDRAPALEM VILLAGE KOYYUR" },
  { name: "PHC -REKHAPALL", type: "PHC", location: "Vararamachandrapuram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: REKHAPALLY VILLAGE V R PURAM MANDAL 533349" },
  { name: "PHC -RUDAKOTA", type: "PHC", location: "Pedabayalu - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: RUDAKOTA VILLAGE PEDABAYALU" },
  { name: "PHC -SAPPARLA", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: SAPPARLA POST" },
  { name: "PHC -SILERU", type: "PHC", location: "G.K VEEDHI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: SILERU MAIN ROAD OPP APGENCO" },
  { name: "PHC -SUNKARAMETTA", type: "PHC", location: "Araku Valley - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: SUNKARAMETTA ARAKUVALLEY MAN" },
  { name: "PHC -TAJANGI", type: "PHC", location: "CHINTAPALLI - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: TAJANGI VILLAGE CHINTHAPALLI" },
  { name: "PHC -TULASIPAKALU", type: "PHC", location: "Addateegala - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: EDUGURALLAPALLY VILLAGE CHINTOOR MANDAL 533347" },
  { name: "PHC -U. CHEEDIPALEM", type: "PHC", location: "Koyyuru - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: UCheedipalem PINCODE-531087" },
  { name: "PHC -UPPA", type: "PHC", location: "Hukumpeta - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: Beside church PINCODE-" },
  { name: "PHC -VADAPALLI", type: "PHC", location: "Rampachodavaram - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: cheruvuru Street Near Santha Market" },
  { name: "PHC -YELLAVARAM", type: "PHC", location: "Addateegala - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "-", image: null, details: "Address: 1-1Main RoadYellavaramV Addateegala MandalPIN 533428" },
  { name: "PHC -ZEDDANGI", type: "PHC", location: "Rajavommangi - R", bedAvailability: "N/A", specialists: ["GYNAECOLOGY AND OBSTETRICS SURGERY"], contact: "9281068506", image: null, details: "Address: zaddangi near police station" },
];
